In [1]:
import numpy as np
list_ = [ '1' , '2' , '3' , '5' , '6' ]
array_list = np.array(object = list_)

Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
    to print the data types of both the variables

In [6]:
# yes there is a diffrance betweent them 

print(type(list_))
print(type(array_list))



<class 'list'>
<class 'numpy.ndarray'>


Q2. Write a code to print the data type of each and every element of both the variables list_ and
arra_list.

In [7]:
for i in list_:
    print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [8]:
for i in array_list:
    print(type(i))

<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


Considering the following changes in the variable, array_list:
array_list = np.array(object = list_, dtype = int)
Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.

In [13]:
array_list = np.array(object = list_, dtype = int)
for i in range(len(array_list)):
    if (type(list_[i]) != type(array_list[i])):
        print(type(list_[i]) , type(array_list[i]))
    

<class 'str'> <class 'numpy.int32'>
<class 'str'> <class 'numpy.int32'>
<class 'str'> <class 'numpy.int32'>
<class 'str'> <class 'numpy.int32'>
<class 'str'> <class 'numpy.int32'>


In [14]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size

In [16]:
num_array.shape

(2, 3)

In [17]:
num_array.size

6

Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.

In [35]:
arr = np.zeros((3,3))

arr.reshape(3,3)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

Q6. Create an identity matrix of shape (5,5) using numpy functions?

In [29]:
arr_z= np.zeros((5,5))

arr_z

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [34]:
import numpy as np

identity_matrix = np.identity(5)
print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
